[app]
name = "TaskManager"
version = "1.0.0"
description = "مدیریت کارها"
org = "MoriZoki"
build-number = "1"

[android]
package-name = "com.morizoki.taskmanager"
version-code = 1
key-store-path = ""
key-alias = ""
key-password = ""
store-password = ""