[app]
name = "TaskManager"
version = "1.0.0"
description = "مدیریت کارها"
executable-name = "taskmanager"
copyright = "Copyright (c) 2025 MoriZoki"
icon = "assets/icon.png"

[android]
package-name = "com.morizoki.taskmanager"
version-code = 1
permissions = ["android.permission.INTERNET"]